   version: '3.8'

services:
  rocketchat:
    image: caseykelso/docker-rocketchat-arm64:7.12.2
    container_name: rocketchat
    restart: unless-stopped
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongodb
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  mongo-init-replica:
    image: mongo:5
    command: >
      bash -c "sleep 10 && mongosh --host mongo:27017 --eval 'rs.initiate({_id:\"rs0\",members:[{_id:0,host:\"mongo:27017\"}]})'"
    depends_on:
      - mongo

volumes:
  mongodb_data:
